#ifndef __BASE_STATES_H__
#define __BASE_STATES_H__

enum class BaseStates_e
{
    BASE_WAITING_TRACKER_SEQ,
    BASE_RECEIVING_TRACKER_SEQ,
    BASE_WAITING_BASE1_SEQ,
    BASE_RECEIVING_BASE1_SEQ,
    BASE_WAITING_BASE2_SEQ,
    BASE_RECEIVING_BASE2_SEQ,
    BASE_TRANSMITTING
};

#endif // __BASE_STATES_H__
